volumes:
  pg_data:
  static:
  media:
  redoc:

services:

  db:
    container_name: tataxon-postgresql
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend: &backend
    container_name: tataxon-backend
    build: ./tataxon_bot
    env_file: .env
    volumes:
      - static:/var/html/backend_static/
      - media:/app/media
    depends_on:
      - db

  nginx:
    container_name: tataxon-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
    
  redis:
    container_name: tataxon-redis
    image: redis:latest
    env_file: .env
    environment:
      - REDIS_PORT=6379
    command: ["redis-server", "--port", "${REDIS_PORT}", "--appendonly", "yes","--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6380:6379"
    volumes:
      - .:/redis.conf
    
  celery-worker:
    <<: *backend
    container_name: celery-worker
    command: -A tataxon_bot.celery worker --loglevel=INFO --pidfile=''
    volumes:
    - .:/var/www/app/worker
    depends_on:
    - db
    - redis

  celery-beat:
    <<: *backend
    container_name: celery-beat
    command: -A tataxon_bot beat --loglevel=INFO
    volumes:
    - .:/var/www/app/beat
    depends_on:
    - celery-worker
    - redis
